export const subscriptions = [
	{
		id: 1,
		name: "basic",
		label: "Basic",
		features: ["1 Lotto Display Screen"],
		price: 20,
		color: "#00cba5",
		screens: [1],
		live: false,
	},
	{
		id: 2,
		name: "standard",
		label: "Standard",
		features: ["1 Lotto Display Screen", "Live Updates"],
		price: 25,
		color: "#fcba39",
		screens: [1],
		live: true,
	},
	{
		id: 3,
		name: "ultimate",
		label: "Ultimate",
		features: ["2 Lotto Display Screen", "Live Updates"],
		price: 40,
		color: "#f96c6c",
		screens: [1, 2],
		live: true,
	},
	{
		id: 4,
		name: "premium",
		label: "Premium",
		features: [
			"1 Lotto Display Screen",
			"Live Updates",
			"2 Ads Display Screen",
		],
		price: 55,
		color: "#808081",
		screens: [1, 3, 4],
		live: true,
	},
	{
		id: 5,
		name: "business",
		label: "Business",
		features: [
			"2 Lotto Display Screen",
			"Live Updates",
			"3 Ads Display Screen",
		],
		price: 65,
		color: "#a8821a",
		screens: [1, 2, 3, 4, 5],
		live: true,
	},
];
